DROP TABLE IF EXISTS IP_POOL;

CREATE TABLE IP_POOL (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  description VARCHAR(250) NOT NULL,
  total_capacity VARCHAR(250) NOT NULL,
  used_capacity VARCHAR(250) DEFAULT NULL,
  lower_bound VARCHAR(250) DEFAULT NULL,
  upper_bound VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS IP_ADDRESS;

CREATE TABLE IP_ADDRESS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  POOL_ID VARCHAR(250) NOT NULL,
  VALUE VARCHAR(250) NOT NULL,
  RESOURCE_STATE VARCHAR(250) DEFAULT NULL
);